package com.charleex.vidgenius.open_ai.model.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject

/**
 * The name and arguments of a function that should be called, as generated by the model.
 */
@Serializable
data class FunctionCall(
    /**
     * The name of the function to call.
     */
    @SerialName("name") val name: String? = null,

    /**
     * The arguments to call the function with, as generated by the model in JSON format.
     * Note that the model does not always generate valid JSON, and may hallucinate parameters
     * not defined by your function schema.
     * Validate the arguments in your code before calling your function.
     */
    @SerialName("arguments") val arguments: String? = null
)
