package src.charleex.vidgenius.whisper.model.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
@Serializable
data class ChatChunk(
    /**
     * Chat choice index.
     */
    @SerialName("index") val index: Int? = null,
    /**
     * The generated chat message.
     */
    @SerialName("delta") val delta: ChatDelta? = null,

    /**
     * The reason why OpenAI stopped generating.
     */
    @SerialName("finish_reason") val finishReason: String? = null,
)
