package src.charleex.vidgenius.whisper.model.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ChatMessage(
    /**
     * The role of the author of this message.
     */
    @SerialName("role") val role: String,

    /**
     * The contents of the message.
     */
    @SerialName("content") val content: String,

    /**
     * The name of the author of this message.
     * [name] is required if role is `[ChatRole.Function], and it should be the name of the function whose response is
     * in the [content]. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
     */
    @SerialName("name") public val name: String? = null,

    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    @SerialName("function_call") public val functionCall: FunctionCall? = null
)
